### ISSUE TITLE
Global config

### ISSUE THREAD

**Issue by Anubz** [inouet/kettle#2]
Hi there!!! Is there a way to config kettle on a global way?
Really good work!! Thanks in advance.
Cheers from Brazil.

**Comment by inouet** [comment]
Hi 

What mean by a "Global Way"?

Thanks.

**Comment by Anubz** [comment]
I saw that you configure the AWS credentials in each controller, right? When I asked for a global way, i mean to wright only one time, on config folder with a specific file. 

Thank you again for your great work!!!

**Comment by inouet** [comment]
It is not required to set AWS credentials in each controllers.
Once you have set, the credentials is re-used.

See code following.

```php
<?php
// FILE: config.php

use Kettle\ORM;

ORM::configure("key",   "xxxx");
ORM::configure("secret", "xxxx");
ORM::configure("region", "xxxx");

```

```php
<?php
// FILE: User.php

use Kettle\ORM;

class User extends ORM 
{
    
}
```

```php
<?php
// FILE: test.php
require_once 'config.php';

use Kettle\ORM;

$user = ORM::factory("User");

```

If you want to use  IAM Role, please use v0.2.0.
IAM Role is used if omitted the key and secret. Instead, please specify the "profile" option.

Thanks!

**Comment by Anubz** [comment]
Amazing work dude!!
Thank you!!!
